---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.34.37"}]
  synced_folders:
  #  - ["data/%{instance_name}", "/shared"]
  #username: ubuntu
   - ["synced", "/synced"]


provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      customize:
        memory: 1024

suites:
  - name: default
    run_list:
      - recipe[cwb-jmeter::default]
    attributes:
      cwbjmeter:
        config:
          ssh_username: 'vagrant'
        target_host:
          name:  '192.168.34.34'
