---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.34.34"}]
  synced_folders:
   - ["synced", "/synced"]

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      customize:
        memory: 512

suites:
  - name: default
    run_list:
      - recipe[acmeair_wlp_morphia::default]
    attributes: